#!/bin/sh
echo "tModLoader: $(./get-mod-version.sh https://github.com/tModLoader/tModLoader)"
echo "AlchemistNPC: $(./get-mod-version.sh https://github.com/VVV101/AlchemistNPC)"
echo "AlchemistNPClite: $(./get-mod-version.sh https://github.com/VVV101/AlchemistNPClite)"
echo "BossChecklist: $(./get-mod-version.sh https://github.com/JavidPack/BossChecklist)"
echo "CalamityMod: $(./get-mod-version.sh https://github.com/MountainDrew8/CalamityMod)"
echo "CalamityModMusic: $(./get-mod-version.sh https://github.com/CalamityTeam/CalamityModMusicPublic)"
echo "ExtensibleInventory: $(./get-mod-version.sh https://github.com/hamstar0/tml-extensibleinventory-mod)"
echo "Fargowiltas: $(./get-mod-version.sh https://github.com/Fargowilta/Fargowiltas)"
echo "FargowiltasSouls: $(./get-mod-version.sh https://github.com/Fargowilta/FargowiltasSouls)"
echo "FargowiltasSoulsDLC: $(./get-mod-version.sh https://github.com/Fargowilta/FargowiltasSoulsDLC)"
echo "MagicStorageExtra: $(./get-mod-version.sh https://github.com/ExterminatorX99/MagicStorageExtra)"
echo "RecipeBrowser: $(./get-mod-version.sh https://github.com/JavidPack/RecipeBrowser)"
echo "TerrariaOverhaul: $(./get-mod-version.sh https://github.com/Mirsario/TerrariaOverhaul)"
echo "ThoriumMod: $(./get-mod-version.sh https://github.com/SamsonAllen13/ThoriumMod)"
echo "Tremor: $(./get-mod-version.sh https://github.com/IAmBatby/Tremor)"
echo "WingSlot: $(./get-mod-version.sh https://github.com/abluescarab/tModLoader-WingSlot)"