#!/bin/sh
echo "tModLoader: $(./get-mod-version.sh https://github.com/tModLoader/tModLoader/releases/latest)"
echo "BossChecklist: $(./get-mod-version.sh https://github.com/JavidPack/BossChecklist/releases/latest)"
echo "CalamityMod: $(./get-mod-version.sh https://github.com/MountainDrew8/CalamityMod/releases/latest)"
echo "CalamityModMusic: $(./get-mod-version.sh https://github.com/CalamityTeam/CalamityModMusicPublic/releases/latest)"
echo "DBZMOD: $(./get-mod-version.sh https://github.com/dbtr/DBZMOD/releases/latest)"
echo "ExtensibleInventory: $(./get-mod-version.sh https://github.com/hamstar0/tml-extensibleinventory-mod/releases/latest)"
echo "Fargowiltas: $(./get-mod-version.sh https://github.com/Fargowilta/Fargowiltas/releases/latest)"
echo "FargowiltasSouls: $(./get-mod-version.sh https://github.com/Fargowilta/FargowiltasSouls/releases/latest)"
echo "FargowiltasSoulsDLC: $(./get-mod-version.sh https://github.com/Fargowilta/FargowiltasSoulsDLC/releases/latest)"
echo "MagicStorageExtra: $(./get-mod-version.sh https://github.com/ExterminatorX99/MagicStorageExtra/releases/latest)"
echo "RecipeBrowser: $(./get-mod-version.sh https://github.com/JavidPack/RecipeBrowser/releases/latest)"
echo "TerrariaOverhaul: $(./get-mod-version.sh https://github.com/Mirsario/TerrariaOverhaul/releases/latest)"
echo "ThoriumMod: $(./get-mod-version.sh https://github.com/SamsonAllen13/ThoriumMod/releases/latest)"
echo "Tremor: $(./get-mod-version.sh https://github.com/IAmBatby/Tremor/releases/latest)"
echo "WingSlot: $(./get-mod-version.sh https://github.com/abluescarab/tModLoader-WingSlot/releases/latest)"